SET search_path TO services_schema;

DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS identity CASCADE;
DROP TABLE IF EXISTS association CASCADE;
DROP TABLE IF EXISTS qualification CASCADE;
DROP TABLE IF EXISTS person_qualification CASCADE;
DROP TABLE IF EXISTS learning_resource CASCADE;
DROP TABLE IF EXISTS learning_record CASCADE;
DROP TABLE IF EXISTS phone CASCADE;
DROP TABLE IF EXISTS person_phone CASCADE;
DROP TABLE IF EXISTS email CASCADE;
DROP TABLE IF EXISTS person_email CASCADE;
DROP TABLE IF EXISTS facility CASCADE;
DROP TABLE IF EXISTS organization_facility CASCADE;  
DROP TABLE IF EXISTS employment_record CASCADE;
DROP TABLE IF EXISTS employment_qualification CASCADE;
DROP TABLE IF EXISTS military_record CASCADE;
DROP TABLE IF EXISTS client_token CASCADE;
DROP TABLE IF EXISTS goal CASCADE;
DROP TABLE IF EXISTS goal_credential CASCADE;
DROP TABLE IF EXISTS goal_competency CASCADE;
DROP TABLE IF EXISTS goal_learning_resource CASCADE